___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
    or
    
    pip install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**




## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [13]:
x=np.array(my_matrix)
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange
 #Syntax
  <code> arrange(start,stop,step,dtype) </Code>
  
Return evenly spaced values within a given interval.

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### zeros and ones

Generate arrays of zeros or ones

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [23]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [87]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [26]:
np.random.rand(2)

array([0.91818056, 0.69848909])

In [27]:
np.random.rand(5,5)

array([[0.7808142 , 0.85447097, 0.11745121, 0.14561674, 0.88754869],
       [0.81410646, 0.89688773, 0.52235003, 0.93005462, 0.01991087],
       [0.54416244, 0.55473069, 0.61126583, 0.8666433 , 0.14084485],
       [0.57278419, 0.86067697, 0.170985  , 0.81608038, 0.7830498 ],
       [0.1170723 , 0.44502042, 0.83167796, 0.25044069, 0.6757778 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [28]:
np.random.randn(5)

array([ 0.47531709, -0.71161887, -0.29955483, -0.6224294 , -1.54166263])

In [21]:
np.random.randn(5,5)

array([[-0.28657364, -1.31109603, -1.5312153 , -0.10084295,  0.40876358],
       [ 0.40564285,  0.71873698,  0.38990879,  0.71048123,  0.22810021],
       [ 0.45141579, -0.20031086,  0.10572891, -0.39510593, -0.45972496],
       [ 0.08880115,  0.84293559,  0.6763124 ,  0.61877546,  1.92070675],
       [-0.08221765, -0.50803748, -0.36392627, -1.29282737,  0.4395613 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(1,100)

58

In [34]:
np.random.randint(1,100,20)

array([94, 66, 94, 70, 29, 28, 33, 69, 94, 29, 79, 69, 35,  7, 86,  8, 55,
       78, 85, 51])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr

array([31, 14,  4,  7, 10, 43, 40, 23, 40, 27])

## Reshape
Returns an array containing the same data with a new shape.

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr.reshape(2,5)

array([[31, 14,  4,  7, 10],
       [43, 40, 23, 40, 27]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
ranarr

array([31, 14,  4,  7, 10, 43, 40, 23, 40, 27])

In [41]:
ranarr.max()

43

In [42]:
ranarr.argmax()

5

In [43]:
ranarr.min()

4

In [44]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [45]:
# Vector
ranarr.shape

(10,)

In [46]:
# Notice the two sets of brackets
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.reshape(5,5).shape

(5, 5)

In [49]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [50]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [51]:
arr.dtype

dtype('int32')

**ndarray.ndim**

This array attribute returns the number of array dimensions.

In [41]:
# an array of evenly spaced numbers 
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
#a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


**numpy.itemsize**

This array attribute returns the length of each element of array in bytes.

In [54]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int32) 
print (x.itemsize)

4


In [55]:
# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

4


In [56]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [57]:
import numpy as np 
x = np.empty([3,3], dtype = float) 
print( x)

#Note − The elements in an array show random values as they are not initialized.

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**numpy.asarray**

This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

numpy.asarray(a, dtype = None, order = None)

In [47]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [48]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


**numpy.frombuffer**

This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

<Code>numpy.frombuffer(buffer, dtype = float, count = 0, offset = 0)</Code>

In [49]:
import numpy as np 
s = b'Hello World' 
a = np.frombuffer(s, dtype = 'S1') 
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [53]:
res=np.frombuffer(b'\x01\x02\x03\x04',dtype=np.uint8,count=4)
print(res)

[1 2 3 4]


**numpy.fromiter**

This function builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.

<Code>numpy.fromiter(iterable, dtype, count = -1)</Code>

The following examples show how to use the built-in range() function to return a list object. An iterator of this list is used to form an ndarray object.

In [54]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)

[0. 1. 2. 3. 4.]


# Great Job!