# Trignometric Functions

numpy provides the ufuncs sin(),cos() and tan()that takes values in radians and produces the corresponding sin, cos and tan values.

In [1]:
import numpy as np
x= np.sin(np.pi/2)
print(x)
arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/6])  #90 60 45 30
x= np.sin(arr)
x

1.0


array([1.        , 0.8660254 , 0.70710678, 0.5       ])

In [2]:
arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/6])
x= np.deg2rad(arr)
x

array([0.02741557, 0.01827705, 0.01370778, 0.00913852])

In [3]:
arr = np.array([90,180,270,360])
x= np.rad2deg(arr)
x

array([ 5156.62015618, 10313.24031235, 15469.86046853, 20626.48062471])

**Finding Angles**
finding angles from values of sin cos tan . Inverse of sin cos tan
arcsin() arccos() arctan()

In [5]:
x= np.arcsin(0.5)
x
np.degrees(x)

30.000000000000004

# Functions for Rounding

**numpy.around()**
This the function that returns the value rounded to the desired precision.The functions takes the following params

<Code> numpy.around(a,decimals) </Code>
  where a - Input data
        decimals - The number of decimal to round to default is 0

In [3]:
a= np.array([1.0,5.55,123,0.567,25.532])

print('Original array is')
print(a)
print('\n')

print('After Rounding:')
print(np.around(a))
print(np.around(a,decimals=1))
print(np.around(a,decimals=2))

Original array is
[  1.      5.55  123.      0.567  25.532]


After Rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  1.     5.55 123.     0.57  25.53]


**numpy.floor()**
This functions returns the largest integer not greater than the input paramter. The floor of the scalar x is the largest integer i such that i<=x.

Note:- In python flooring is always rounded away from 0.

In [7]:
a= np.array([-1.7,1.5,-0.2,0.6,10])

print('the Given array is :')
print(a)
print('\n')

print('the modified array is :')
print(np.floor(a))

the Given array is :
[-1.7  1.5 -0.2  0.6 10. ]


the modified array is :
[-2.  1. -1.  0. 10.]


**numpy.ceil()**
The ceil of the scalar x is the smallest integer i such that i>=x

In [13]:
print(np.ceil(a))

[-1.  2. -0.  1. 10.]
