1. How create an empty and full numpy array?

In [4]:
import numpy as np
arr =  np.empty((2,2))
arr

np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

2. Create a numpy array filled with all zeroes 


In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

 3. How to Extract items that satisfy a given condition from 1D Array.
 
    arr = np.array([0,1,2,3,4,5,6,7,8,9])
    
    output = array([1,3,5,7,9])

In [8]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

4. Replace all odd numbers in array with -1   (without changing the original array !optional )  
   arr = np.array([0,1,2,3,4,5,6,7,8,9])
    
    output = array([0,-1,2,-1,4,-1,6,-1,8,-1])

In [10]:
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr1 = np.arange(10)
out = np.where(arr1%2==1,-1,arr1)
print("Modified array is " , out)
print("Original array is " , arr1)

Modified array is  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original array is  [0 1 2 3 4 5 6 7 8 9]


5. How to Generate Custom sequences in numpy without hardcoding.
   a = np.array([1,2,3])
   
   output = array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3

6. Get the common items between array A and B
   input:
      a = [1,2,3,2,3,4,3,4,5,6]
      b = [7,2,10,2,7,4,9,4,9,8]
      
   output: 
       [2,4]