NumPy package contains a Matrix library numpy.matlib. This module has functions that return matrices instead of ndarray objects.

**matlib.empty()**

The matlib.empty() function returns a new matrix without initializing the entries. The function takes the following parameters.

 **numpy.matlib.empty(shape, dtype, order)**
 
Where,

1	
shape

int or tuple of int defining the shape of the new matrix

2	
Dtype

Optional. Data type of the output

3	
order

C or F

In [3]:
import numpy.matlib 
import numpy as np 

print(np.matlib.empty((3,3),dtype=int) )
# filled with random data

[[5242959 5111877 4980802]
 [5439553 5046367 4784193]
 [6225998 5374022 4522053]]


**numpy.matlib.zeros()**

This function returns the matrix filled with zeros.

In [4]:
import numpy.matlib 
import numpy as np 
print (np.matlib.zeros((2,2))) 

[[0. 0.]
 [0. 0.]]


numpy.matlib.ones()
This function returns the matrix filled with 1s.

In [5]:
import numpy.matlib 
import numpy as np 
print( np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


numpy.matlib.eye()
This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere. The function takes the following parameters.

numpy.matlib.eye(n, M,k, dtype)
Where,

Sr.No.	Parameter & Description
1	
n

The number of rows in the resulting matrix

2	
M

The number of columns, defaults to n

3	
k

Index of diagonal

4	
dtype

Data type of the output



In [6]:
import numpy.matlib 
import numpy as np 
print( np.matlib.eye(n = 3, M = 4, k = 2, dtype = float))

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


numpy.matlib.identity()

The numpy.matlib.identity() function returns the Identity matrix of the given size. An identity matrix is a square matrix with all diagonal elements as 1.

In [8]:
import numpy.matlib 
import numpy as np 
print( np.matlib.identity(4, dtype = float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
numpy.matlib.rand()

The numpy.matlib.rand() function returns a matrix of the given size filled with random values.

In [8]:
import numpy.matlib 
import numpy as np 
print( np.matlib.rand(3,3))

[[0.8807783  0.61939079 0.2830526 ]
 [0.89289988 0.73345998 0.26424233]
 [0.53616732 0.93015255 0.59734515]]


Note that a matrix is always two-dimensional, whereas ndarray is an n-dimensional array. Both the objects are inter-convertible.

In [9]:
import numpy.matlib 
import numpy as np  

i = np.matrix('1,2,5;3,4,6;5,6,7') 
print( i) 

[[1 2 5]
 [3 4 6]
 [5 6 7]]


In [10]:
import numpy.matlib 
import numpy as np  

j = np.asarray(i) 
print (j) 

[[1 2 5]
 [3 4 6]
 [5 6 7]]


In [12]:
import numpy.matlib 
import numpy as np  

k = np.asmatrix (j) 
print (k)

[[1 2 5]
 [3 4 6]
 [5 6 7]]
