NumPy package contains numpy.linalg module that provides all the functionality required for linear algebra. Some of the important functions in this module are described in the following table.

Sr.No.	Function & Description

1	dot
    Dot product of the two arrays

2	vdot
    Dot product of the two vectors

3	inner
   Inner product of the two arrays

4	matmul
   Matrix product of the two arrays

5	determinant
Computes the determinant of the array

6	solve
Solves the linear matrix equation

7	inv
Finds the multiplicative inverse of the matrix



In [2]:
import numpy as np
a=7+ 2j   #=> (7+2j).(5+5j) = 7*5 + 2j*5j + 7.5j+2j*5
b=5 + 5j
print(np.vdot(a,b))
print(np.inner(a,b))

(45+25j)
(25+45j)


In [3]:
a=[[2,1],[0,3]]  #2,1 = >               2.1 + 1.3  2.1+ 1.2   5 4
                 #0,3 =>                0.1 + 3.3   0.1+3.2   9 6
b=[[1,1],[3,2]] # 1,1 => 1+1j
                 #3,2 => 3+2j
print(np.dot(a,b))

[[5 4]
 [9 6]]


In [4]:
A= [[1,5,3],[4,6,6],[3,8,9]]  #3*3
B= [[1,5,3,4],[4,5,7,8],[7,8,9,3]]  #3*4
print(np.array(A))
print(np.array(B))
np.matmul(A,B) #3*4

[[1 5 3]
 [4 6 6]
 [3 8 9]]
[[1 5 3 4]
 [4 5 7 8]
 [7 8 9 3]]


array([[ 42,  54,  65,  53],
       [ 70,  98, 108,  82],
       [ 98, 127, 146, 103]])

In [5]:
#Determinanat
import numpy.linalg as la
A= [[-1,3,0],[2,1,-5],[1,4,-2]]    
print(np.array(A))
la.det(A)

[[-1  3  0]
 [ 2  1 -5]
 [ 1  4 -2]]


-21.00000000000001

In [19]:
#Inverse of a Matrix
la.inv(A)  #== A = |A|\

array([[-0.85714286, -0.28571429,  0.71428571],
       [ 0.04761905, -0.0952381 ,  0.23809524],
       [-0.33333333, -0.33333333,  0.33333333]])