A variety of functions are available in numpy for sorting

1.merge sort

2.quick sort

3.heapsort

# numpy.sort()

This function return a sorted copy of the input array

   Syntax - numpy.sort(a,axis,kind,order)

In [1]:
import numpy as np
a= np.array([[10,7,6],[9,1,12]])

print("Array is....")
print(a)

print("Apply sorting....")
print(np.sort(a))

print("apply sorting columns wise")
print(np.sort(a,0))

Array is....
[[10  7  6]
 [ 9  1 12]]
Apply sorting....
[[ 6  7 10]
 [ 1  9 12]]
apply sorting columns wise
[[ 9  1  6]
 [10  7 12]]


# numpy.argsort()

The numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.


In [20]:
import numpy as np 
x = np.array([13, 10, 20]) 

print( 'Our array is:') 
print(x) 
print ('\n' ) 

print ('Applying argsort() to x:') 
y = np.argsort(x) 
print(y) 
print( '\n')  

print ('Reconstruct original array in sorted order:' )
print( x[y]) 
print ('\n')  

print ('Reconstruct the original array using loop:' )
for i in y: 
   print( x[i])


Our array is:
[13 10 20]


Applying argsort() to x:
[1 0 2]


Reconstruct original array in sorted order:
[10 13 20]


Reconstruct the original array using loop:
10
13
20


# numpy.lexsort()

function performs an indirect sort using a sequence of keys. The keys can be seen as a column in a spreadsheet. The function returns an array of indices, using which the sorted data can be obtained. Note, that the last key happens to be the primary key of sort.

In [21]:
import numpy as np 

nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 

print ('Applying lexsort() function:' )
print (ind) 

print ('Use this index to get sorted data:') 
print ([nm[i] + ", " + dv[i] for i in ind] )

Applying lexsort() function:
[3 1 0 2]
Use this index to get sorted data:
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


# numpy.argmax() and numpy.argmin()

These two functions return the indices of maximum and minimum elements respectively along the given axis.

In [2]:
import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print('Our array is:') 
print( a) 
 

print ('Applying argmax() function:') 
print(np.argmax(a))

print('Index of maximum number in flattened array' )
print( a.flatten() )


print ('Array containing indices of maximum along axis 0:' )
maxindex = np.argmax(a, axis = 0) 
print (maxindex)
print ('\n' )

print ('Array containing indices of maximum along axis 1:' )
maxindex = np.argmax(a, axis = 1) 
print( maxindex)
print ('\n' )

print ('Applying argmin() function:')
minindex = np.argmin(a) 
print(minindex)
print ('\n' )
   
print ('Flattened array:')
print(a.flatten()[minindex])
print ('\n' )  

print( 'Flattened array along axis 0:')
minindex = np.argmin(a, axis = 0) 
print( minindex)
print ('\n' )

print( 'Flattened array along axis 1:' )
minindex = np.argmin(a, axis = 1) 
print( minindex)


Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]
Applying argmax() function:
7
Index of maximum number in flattened array
[30 40 70 80 20 10 50 90 60]
Array containing indices of maximum along axis 0:
[1 2 0]


Array containing indices of maximum along axis 1:
[2 0 1]


Applying argmin() function:
5


Flattened array:
10


Flattened array along axis 0:
[0 1 1]


Flattened array along axis 1:
[0 2 0]


# numpy.nonzero()

The numpy.nonzero() function returns the indices of non-zero elements in the input array.

In [4]:
import numpy as np 
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
    #00,01,11,12,20,22
print( 'Our array is:') 
print( a) 
print ('\n')  

print( 'Applying nonzero() function:') 
x= np.nonzero (a);
print(a[x])

Our array is:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]


Applying nonzero() function:
[30 40 20 10 50 60]


# numpy.where()

The where() function returns the indices of elements in an input array where the given condition is satisfied.

In [6]:
import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print( 'Our array is:') 
print( x)  

print( 'Indices of elements > 3') 
y = np.where(x>3) 
print( y)  

print( 'Use these indices to get elements satisfying the condition') 
print( x[y])

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Indices of elements > 3
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


# numpy.extract()
The extract() function returns the elements satisfying any condition.

In [8]:
import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print( 'Our array is:') 
print( x)  

# define a condition 
condition = np.mod(x,2) == 0 

print ('Element-wise value of condition') 
print( condition  )

print( 'Extract elements using condition')
print( np.extract(condition, x))

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]
Extract elements using condition
[0. 2. 4. 6. 8.]


# NUMPY − BYTE SWAPPING

We have seen that the data stored in the memory of a computer depends on which architecture the CPU uses. It may be little-endian (least significant is stored in the smallest address) or big-endian (most significant byte in the smallest address).

**numpy.ndarray.byteswap() **

The numpy.ndarray.byteswap() function toggles between the two representations: bigendian and little-endian.     

In [16]:
import numpy as np 
a = np.array([1, 256, 8755], dtype = np.int16) 

print( 'Our array is:' )
print( a)  

print( 'Representation of data in memory in hexadecimal form:')  
print(list( map(hex,a)))  
# byteswap() function swaps in place by passing True parameter 

print( 'Applying byteswap() function:') 
print( a.byteswap(True)) 

print( 'In hexadecimal form:' )
print(list( map(hex,a))) 
# We can see the bytes being swapped

Our array is:
[   1  256 8755]
Representation of data in memory in hexadecimal form:
['0x1', '0x100', '0x2233']
Applying byteswap() function:
[  256     1 13090]
In hexadecimal form:
['0x100', '0x1', '0x3322']


# NUMPY − COPIES & VIEWS

While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is called Copy. If on the other hand, a different view of the same memory content is provided, we call it as View.

**No Copy**

Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it. The id() returns a universal identifier of Python object, similar to the pointer in C.

Furthermore, any changes in either gets reflected in the other. For example, the changing shape of one will change the shape of the other too.

In [9]:
import numpy as np 
a = np.arange(6) 

print( 'Our array is:' )
print( a ) 

print( 'Applying id() function:' )
print( id(a))  

print( 'a is assigned to b:') 
b = a 
print( b)  

print( 'b has same id():') 
print( id(b))  

print( 'Change shape of b:') 
b.shape = 3,2 
print( b)  

print( 'Shape of a also gets changed:') 
print( a)

Our array is:
[0 1 2 3 4 5]
Applying id() function:
1962869204912
a is assigned to b:
[0 1 2 3 4 5]
b has same id():
1962869204912
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


# View or Shallow Copy

NumPy has ndarray.view() method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn’t change dimensions of the original.

In [18]:
import numpy as np 
# To begin with, a is 3X2 array 
a = np.arange(6).reshape(3,2) 

print( 'Array a:') 
print( a)  

print( 'Create view of a:' )
b = a.view() 
print( b)  

print ('id() for both the arrays are different:' )
print( 'id() of a:')
print (id(a)  )
print( 'id() of b:') 
print (id(b)  )

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

b[0,0]=100
print( 'Shape of b:') 
print (b)  

print( 'Shape of a:') 
print (a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
1311138910928
id() of b:
1311138911024
Shape of b:
[[100   1   2]
 [  3   4   5]]
Shape of a:
[[100   1]
 [  2   3]
 [  4   5]]


In [ ]:
import numpy as np 
a = np.array([[10,10], [2,3], [4,5]]) 

print 'Our array is:' 
print a  

print 'Create a slice:' 
s = a[:, :2] 
print s 

**Deep Copy**

The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

In [26]:
import numpy as np 
a = np.array([[10,10], [2,3], [4,5]]) 

print( 'Array a is:') 
print( a  )

print ('Create a deep copy of a:' )
b = a.copy() 
print( 'Array b is:' )
print( b )

#b does not share any memory of a 
print( 'Can we write b is a' )
print( b is a  )

print ('Change the contents of b:' )
b[0,0] = 100 

print ('Modified array b:' )
print (b)  

print ('a remains unchanged:' )
print (a)

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Can we write b is a
False
Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]
