# Changing Shape
1.**Reshape**
 It gives new shape to an array without changing its data.
 
2.**Flat**
 A 1-D iterator over the array
 
3.**flatten**
 Returns a copy of the array collapsed into one dimension
 
4.**ravel**
 Returns a contiguous flattened array

In [3]:
import numpy as np
a = np.arange(9).reshape(3,3)
print("The original array:..")
print(a)

print("After applying the flat function:")
print(a.flat[7])

print("After applying flatten function:")
print(a.flatten())

print("The flattened array in F-style ordering:")
print(a.flatten(order='F'))

print("After applying ravel function:")
print(a.ravel())

The original array:..
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After applying the flat function:
7
After applying flatten function:
[0 1 2 3 4 5 6 7 8]
The flattened array in F-style ordering:
[0 3 6 1 4 7 2 5 8]
After applying ravel function:
[0 1 2 3 4 5 6 7 8]


# Transpose operations
1.**transpose**
  permutes the dimensions of an array
  
2. **ndarray.T**
  same as self.transpose
  
3. **rollaxis**  
   syntax = rollaxis(arr,axis,start=0)
  Rolls the specified axis backwards
  
4. **swapaxes**
    syntax =  swapaxes(arr,source,dest)
  Interchanges the two axes of an array

In [30]:
a = np.arange(12).reshape(3,4)

print("The origninal array is :")
print(a)

print("The transposed array is:")
print(np.transpose(a))

print("After applying the ndarray.T")
print(a.T)

a= np.arange(24).reshape(2,4,3)
print("New array is ")
print(a)

d = np.ones((1,2,3,4))
print("After applying rollaxis function")
print(np.rollaxis(d,2))
print("\n")
print(np.rollaxis(d,2,1))


print("After applying rollaxis function")
print(np.rollaxis(a,2))
print("\n")
print(np.rollaxis(a,2,1))

print("After applying the swapaxes")
print(np.swapaxes(a,2,1))

The origninal array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
After applying the ndarray.T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
New array is 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
After applying rollaxis function
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
After applying rollaxis function
[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


[[[ 0  3  6  9]
  [ 1  4  7 10]
  [ 2  5  8 11]]

 [[12 15 18 21]
  [13 16 19 22]
  [14 17 20 23]]]
After applying the swapaxes
[[[ 0  3  6  9]
  [ 1  4  7 10]
  [ 2  5  8 11]]

 [[12 15 18 21]
  [13 16 19 22]
  [14 17 20 23]]]


# changing Dimensions
1. **broadcast**
 produces an object the mimics broadcasting
2. **broadcast_to**
 Boradcasts an array to a new shape
3. **expand_dims**
 Expands the shape of an array
4. **squeeze**
 Removes single-dimensional entries from the shape of an array
 

In [15]:
x= np.array([[1],[2],[3]])
y=np.array([4,5,6])

#broadcasts x aagainst y
b = np.broadcast(x,y)
# it has an iterator property a touple of iteratoralong self's component

r,c = b.iters
#print(next(r))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
#print(next(r), next(c))

1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6


StopIteration: 

**Numpy VStack and hStack**

numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

Syntax : numpy.hstack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the second axis.

Return : [stacked ndarray] The stacked array of the input arrays.

In [16]:
# Python program explaining
# hstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [2]:
import numpy as geek
  
# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


**numpy.vstack() function**

  It is used to stack arrays vertically (row-wise) to make a single array. It takes a sequence of arrays and joins them vertically. This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N).
This function is useful when you have two or more arrays with the same number of columns, and you want to concatenate them vertically (row-wise). It is also useful to append a single array as a new row to an existing 2D array.

In [17]:
import numpy as np
x = np.array([3, 5, 7])
y = np.array([5, 7, 9])
np.vstack((x,y))



array([[3, 5, 7],
       [5, 7, 9]])

In [12]:
A = np.ones((3,4))
B = np.zeros((2,4))
print("A:",A,"\n","B:",B)
vstack = np.vstack((A,B))
print("After applying vstack :\n",vstack)

A: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 B: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
After applying vstack :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**numpy Split : vSplit and hSplit**

numpy.vsplit is a special case of split() function where axis is 1 indicating a vertical split regardless of the dimension of the input array. The following example makes this clear.

In [13]:
import numpy as np 
a = np.arange(16).reshape(4,4) 

print( 'First array:' )
print( a) 
print ('\n')

print( 'Vertical splitting:' )
b = np.vsplit(a,2) 
print(b)

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


numpy.hsplit() function split an array into multiple sub-arrays horizontally (column-wise). hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

Syntax : numpy.hsplit(arr, indices_or_sections)
Parameters :
arr : [ndarray] Array to be divided into sub-arrays.
indices_or_sections : [int or 1-D array] If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis.
If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split
Return : [ndarray] A list of sub-arrays.

In [20]:
# Python program explaining
# numpy.hsplit() function

# importing numpy as geek
import numpy as geek

arr = geek.arange(24.0).reshape(4, 6)
print(arr)
gfg = geek.hsplit(arr, 2)

print (gfg)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[array([[ 0.,  1.,  2.],
       [ 6.,  7.,  8.],
       [12., 13., 14.],
       [18., 19., 20.]]), array([[ 3.,  4.,  5.],
       [ 9., 10., 11.],
       [15., 16., 17.],
       [21., 22., 23.]])]


In [20]:
# Python program explaining
# numpy.hsplit() function

# importing numpy as geek
import numpy as geek

arr = geek.arange(27.0).reshape(3, 3, 3)

print("Original array : " ,arr)

gfg = geek.hsplit(arr, 3)

print (gfg)


Original array :  [[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]
[array([[[ 0.,  1.,  2.]],

       [[ 9., 10., 11.]],

       [[18., 19., 20.]]]), array([[[ 3.,  4.,  5.]],

       [[12., 13., 14.]],

       [[21., 22., 23.]]]), array([[[ 6.,  7.,  8.]],

       [[15., 16., 17.]],

       [[24., 25., 26.]]])]
