# Statistical Functions -Numpy
Numpy has very useful functions for finding minimum , maximum precentile, standard deviation and variance etc....

numpy.amin()

numpy.amax()

In [3]:
import numpy as np
a = np.array([[3,4,5],[8,4,3],[2,4,9]])
print("Our array...")
print(a)

print("Applying min functions....")
print(np.amin(a,1))

print("Applying min function columns wise...")
print(np.amin(a,0))

print("applying max function...")
print(np.amax(a,axis=0))

Our array...
[[3 4 5]
 [8 4 3]
 [2 4 9]]
Applying min functions....
[3 3 2]
Applying min function columns wise...
[2 4 3]
applying max function...
[8 4 9]


numpy.ptp()

It returns the range (max-min) of values along an axis

In [7]:
a = np.array([[3,4,5],[8,4,3],[2,4,9]])
print(a)
print("Overall in matrix :" , np.ptp(a))
print("Row wise :" ,np.ptp(a,axis=1))
print("Column wise :" ,np.ptp(a,axis=0))

[[3 4 5]
 [8 4 3]
 [2 4 9]]
Overall in matrix : 7
Row wise : [2 5 7]
Column wise : [6 0 6]


# np.percentile()
It is a measure used in statistics indicating the value below which a given pecentage of observations in a group of observartions fall.

syntax
   numpy.percentile(a,q,axis) where a=input array, q= the percentile to calculate,axis = row, columns

In [11]:
a = np.array([20,2,7,1,34])
print("Our array...")
print(a)

print("applying percentile...")
print(np.percentile(a,50))

print(np.percentile(a,75))

Our array...
[20  2  7  1 34]
applying percentile...
7.0
20.0


# numpy.median()

its defined as value separating the higher half of data sample from the lower half

In [12]:
a = np.array([[30,40,50],[80,40,30],[20,40,90]])
print("Our array...")
print(a)

print("Applying median...")
print(np.median(a))

print("Applying it on columns...")
print(np.median(a,0))

#20 30 30 40 40 40 50 80 90

Our array...
[[30 40 50]
 [80 40 30]
 [20 40 90]]
Applying median...
40.0
Applying it on columns...
[30. 40. 50.]


# numpy.mean()

It is the sum of elements along an axis divided by the number of elements

In [2]:
import numpy as np
a = np.array([[30,40,50],[80,40,30],[20,40,90]])
print("Our array...")
print(a)

print("Applying mean over rows...")
print(np.mean(a,1))

Our array...
[[30 40 50]
 [80 40 30]
 [20 40 90]]
Applying mean over rows...
[40. 50. 50.]
